inventory:
  options:
    ssl_verify: "./certs/homelab_sub_ca-chain.pem"
  plugin: NetBoxInventory2
runner:
  plugin: threaded
  options:
    num_workers: 10
logging:
  enabled: true
  level: DEBUG
  log_file: nornir.log
  to_console: False
user_defined:
  saved_configs_root: configs