from nornir import InitNornir
from nornir_jinja2.plugins.tasks import template_file
from nornir_netmiko import netmiko_send_config, netmiko_send_command, netmiko_save_config
from nornir.core.task import Task, Result, AggregatedResult
from nornir.core.filter import F
from deepdiff import DeepDiff
from typing import Optional, Any
from pathlib import Path
from getpass import getpass
from logging import DEBUG
from os import environ
from pprint import pprint as pp
from git import Repo

class helper():
    def __init__(self, 
                 config_file: Optional[str] = None, 
                 username: Optional[str] = None, 
                 password: Optional[str] = None, 
                 filter: Optional[F] = None, 
                 **kwargs: Any) -> None:
        
        nr = InitNornir(config_file = config_file) if config_file is not None else InitNornir(**kwargs)

        nr.inventory.defaults.username = username or environ['NORNIR_USERNAME']
        nr.inventory.defaults.password = password or environ['NORNIR_PASSWORD']
        if nr.inventory.defaults.username is None:
            nr.inventory.defaults.username = input("Username: ")
        if nr.inventory.defaults.password is None:
            nr.inventory.defaults.password = getpass("Password: ")

        if filter is not None:
            nr = nr.filter(filter)

        ## pulling from the nornir config file
        ## defaults to empty if no value found
        self.saved_configs_root = nr.config.user_defined.get("saved_configs_path") or ""
        self.template_path = nr.config.user_defined.get("template_path") or ""

        ## make sure saved configuration root folder exists
        Path(f"{self.saved_configs_root}").mkdir(exist_ok = True)

        ## original_nr allows multiple filter calls
        self.nr, self.original_nr = nr, nr

        ## check if configs are managed by git repo
        try:
            self.repo = Repo(self.saved_configs_root)
        except Exception as e:
            self.repo = None


    def _jinja_template(self, task: Task, apply: bool = False) -> Result:
        """
        Generates or applys jinja2 templates to devices.
        
        :param task: Nornir task object
        :param apply: Apply the generated template to the device
        :return: Returns a Nornir Result object with the results of the generation and/or application of the template
        """
        # load data for template
        template_vars = task.host.extended_data()

        # name conflicts with Task/Result object return value
        del template_vars["name"]

        if task.host.platform == "cisco_ios":
            template = "base.j2"

        path = f"{self.template_path}/"
        path += task.host.platform

        changed = False
        failed = False

        # generate template
        generated_template = task.run(task = template_file, template = template, path = path, name = "generate_template", severity_level = DEBUG, **template_vars)
        failed = generated_template.failed

        if apply:
            applied_result = task.run(task = netmiko_send_config, config_commands = generated_template[0].result.splitlines(), severity_level = DEBUG, name = "apply_template")
            failed = applied_result.failed
            changed = applied_result.changed

        return Result(task.host, result = f"host: {task.host} changed: {changed} failed: {failed}", changed = changed, failed = failed)
    
    def filter(self, filter: F) -> None:
        """
        Filter the inventory that was created and the initialization of the object.
        
        :param filter: Nornir filter generated by F
        """
        self.nr = self.original_nr.filter(filter)

    def send_command_all(self, **kwargs: Any) -> AggregatedResult:
        """
        Send a command to all hosts.

        :param kwargs: Any arguments to pass to the netmiko send_command
            Common netmiko send_command args
                command_string
                use_textfsm
                textfsm_template
                use_ttp
                ttp_template


        :return: Returns AggregatedResult from the Nornir.run command.

        """
        return self.nr.run(netmiko_send_command, **kwargs)
    
    def send_config_all(self, **kwargs: Any) -> AggregatedResult:
        """
        Send configuration commands to all hosts at the same time.

        :param kwargs: Any arguments to pass to the netmiko send_config command.
            Common netmiko send_config args
                config_commands
                config_mode_command

        :return: Returns AggregatedResult from the Nornir.run command.
        """
        return self.nr.run(netmiko_send_config, **kwargs)

    def send_command_single(self, task: Task, **kwargs: Any) -> AggregatedResult:
        """
        Send a command to a hosts in their own context.
        
        :param task: Nornir Task
        :param kwargs: Any arguments to pass to the netmiko send_command

        :return: Returns AggregatedResult from the Nornir.run command.

        """
        pass

    def send_config_single(self, task: Task, **kwargs: Any) -> AggregatedResult:
        """
        Send a command to a hosts in their own context.
        
        :param task: Nornir Task
        :param kwargs: Any arguments to pass to the netmiko send_config command.
        
        :return: Returns AggregatedResult from the Nornir.run command.
        """
        pass
    
    def jinja_template(self, **kwargs) -> AggregatedResult:
        """
        Wrapper function to generate or apply jinja2 template configurations for devices.

        :param kwargs: Arugments to pass to the self._template function.
        :return: Returns AggregatedResult from the Nornir.run command.
        """
        return self.nr.run(self._jinja_template, name = "template", **kwargs)
    
    def save_configuration(self) -> AggregatedResult:
        """
        Saves the running-configuration of the device to startup-configuration
        
        :return: Returns AggregatedResult from the Nornir.run command.
        """
        return self.nr.run(netmiko_save_config)
    
    def backup_configuration(self) -> AggregatedResult:
        """
        Backup the configuration of devices to a file.

        If the configuration path `self.saved_configs_root` is a git repository, then any changes will be committed.
        
        :return: Returns the AggregatedResult result of getting the configuration from the device.
        """
        result = self.send_command_all(command_string = "show running-config")
        for host in result:
            with open(f"{self.saved_configs_root}/{host}.txt", "w") as f:
                f.write(result[host][0].result)
            if self.repo is not None:
                self.repo.index.add(f"{host}.txt")
        if self.repo is not None:
            if self.repo.is_dirty():
                self.repo.index.commit("updated configurations")
        return result
    
    def validate_configuration(self) -> None:
        """
        Compares the intended configuration to the actual configuration on the device and displays the differences.

        The intended configuration is pulled from the self.nr object which is pulled from the netbox config context.

        ttp templates used for comparison are stored under ./templates/ttp

        Does not return anything.
        
        """
        result = self.send_command_all(command_string = "show run", use_ttp = True, ttp_template = "./templates/ttp/")
        print("Comparing intended to actual")
        print("-" * 75)
        for host in result:
            print(f"host: {host}")
            for k in self.nr.inventory.hosts[host].data["config_context"]:
                if k in result[host][0].result[0][0]:
                    actual_config = result[host][0].result[0][0][k]
                    intended_config = self.nr.inventory.hosts[host].data["config_context"][k]
                    diff = DeepDiff(intended_config, actual_config)
                    print(f"configuration item: {k}")
                    print("*" * 25)
                    pp(diff, indent = 4) if diff else print("Configurations are identical.")
                    print("-" * 75)
        
        